### ISSUE TITLE
.tar Support!

### ISSUE THREAD

**Issue by Strangelets** [arshsisodiya/helios-mirror#1]
Zip is slow and uses a lot of resources and can you provide an alternative like tar to mirror fastly pls

On HDD Extracting Time

.tar - 7zip 01:10sec Winrar 01:51sec
.zip - 7zip 02:02sec Winrar 02:08sec

On SDD Extracting Time

.tar - 7zip 11sec Winrar 11sec
.zip - 7zip 17sec Winrar 20sec

so .tar is really fast

Dark Desire (2022) S02 720p 10bit WEBRip HEVC [NF Hindi AAC 2.0 128Kbps] ~ (strange) PSA 2.55 GB (2,74,45,24,800 bytes)

Iknow it no compression but still slow Thanks.

**Comment by arshsisodiya** [comment]
I have no plans of Adding tar support for now, zip is working find and 1:09 minutes difference on HDD or 9 seconds diffrence on SSD is not that huge.
