### ISSUE TITLE
4GB leech issue

### ISSUE THREAD

**Issue by narutouzumaki271** [arshsisodiya/helios-mirror#111]
there is a issue in 4GB leech 
if there is file size of 4GB or less than 4GB then there is no splitting and then single uploaded file will be under 4GB
but if file size increase from 4GB let suppose 6GB it will split the files in 2GB and then it upload 
means when file size is above than 4GB then premium leeching doesn't work

**Comment by arshsisodiya** [comment]
no such issue is there
