### ISSUE TITLE
[Improvement] Shifting from telegra.ph to graph.org 

### ISSUE THREAD

**Issue by RealNoobieDrive** [arshsisodiya/helios-mirror#114]
can you change telegra.ph to graph.org ??

**Comment by rahulkhatri137** [comment]
telegra.ph is banned

**Comment by YourGirFriendsBF** [comment]
It still opens in Telegram itself

**Comment by arshsisodiya** [comment]
https://github.com/arshsisodiya/helios-mirror/commit/a94df1b3505f145d39ff3f84bac0ff019fb6bd5a
