### ISSUE TITLE
Leech Bugg

### ISSUE THREAD

**Issue by DreamCatcher96** [arshsisodiya/helios-mirror#118]
Bro when we leech in Group , leech status message all so forwarding in Leech Log channel 😐

Screenshot on Log cahnnel 👇

> It's a feature ffs.

It's possible to do for optional true or false like that

**Comment by arshsisodiya** [comment]
It's a feature ffs.

**Comment by DreamCatcher96** [comment]
> It's a feature ffs.

It's possible make optional

**Comment by DreamCatcher96** [comment]
> > It's a feature ffs.
> 
> It's possible make optional

Or we can stop that fetcher in repo ?  Can u explain how stop that , which lane put hash

**Comment by arshsisodiya** [comment]
Ok, i will make it forward leech index message only when forcebotpm is enable

**Comment by DreamCatcher96** [comment]
> Ok, i will make it forward leech index message only when forcebotpm is enable

Ok bro , thank you very much , Good Work 😍
