### ISSUE TITLE
Can you make the repo compatible/deployable on render?

### ISSUE THREAD

**Issue by BarrenWardo** [arshsisodiya/helios-mirror#119]
I have been using this repo for quite sometime now and I really appreciate your work and efforts here.

Since free heroku is going to die.

Can you make it deployable on [render](https://render.com)? or it might already is (I am not a techy actually)

If it is already deployable then can you atleast make a guide or something for it.

Thank you for your work. Hoping for a positive response.

**Comment by arshsisodiya** [comment]
Render has 100 GB network bandwidth limit, so it's useless,
