### ISSUE TITLE
Cancel comment not working

### ISSUE THREAD

**Issue by DreamCatcher96** [arshsisodiya/helios-mirror#120]
When I try to cancel Mirror or Leech the cancel comment is not working 

Log and screenshot below 👇

[log.txt](https://github.com/arshsisodiya/helios-mirror/files/9440065/log.txt)  👈 Log File is Here

![IMG_20220828_192518](https://user-images.githubusercontent.com/63229691/187084455-c200cdc4-3e2b-4dcf-a09d-cc10dada8119.jpg)

**Comment by arshsisodiya** [comment]
Did you deleted the source message?
Are you mirroring a telegram file.

Eloborate your issue so that we can recreate it.

**Comment by DreamCatcher96** [comment]
> Did you deleted the source message? Are you mirroring a telegram file.
> 
> Eloborate your issue so that we can recreate it.

Iam mirroring in torrent link same issue , leech telegram file same issue , leech index link same issue

**Comment by arshsisodiya** [comment]
> > Did you deleted the source message? Are you mirroring a telegram file.
> > Eloborate your issue so that we can recreate it.
> 
> No , iam not delete source message , Iam mirroring in torrent file or magnetic , leech telegram file , leech index link all same issue
> 
> Cancel comment not respond , without gid comment working
> 
> With gid not respond

Are you using FORCE_BOT_PM?

**Comment by DreamCatcher96** [comment]
> 

No

> 

Iam not using FORCE_BOT_PM

**Comment by DreamCatcher96** [comment]
> 

Iam Not using FORCE_BOT_PM

**Comment by arshsisodiya** [comment]
> > 
> 
> Iam Not using FORCE_BOT_PM

Are you facing this issue when mirroring/leeching by replying the link or when using the command link  "/mirror <link>"

**Comment by DreamCatcher96** [comment]
> > > 
> > 
> > 
> > Iam Not using FORCE_BOT_PM
> 
> Are you facing this issue when mirroring/leeching by replying the link or when using the command link "/mirror "

When I give mirror comment starring mirroring , again I try to cancel that mirroring the comment not respond 

Mirror & Leech same

**Comment by arshsisodiya** [comment]
> > > > 
> > > 
> > > 
> > > Iam Not using FORCE_BOT_PM
> > 
> > 
> > Are you facing this issue when mirroring/leeching by replying the link or when using the command link "/mirror "
> 
> When I give mirror comment starring mirroring , again I try to cancel that mirroring the comment not respond
> 
> Mirror & Leech same
> 
> /mirror Or /leech / qbmirror all same

Im asking are you facing this issue when mirroring by replying the link

"Ex. First send the link and then reply it with mirror command."

Are you doing this?

**Comment by DreamCatcher96** [comment]
![Screenshot_2022-08-28-19-56-21-686_org telegram plus](https://user-images.githubusercontent.com/63229691/187085672-ea8ec855-4d73-4831-89c1-c4701471b73e.jpg)
Long time iam trying to cancel this , but cant its comment not respond

**Comment by DreamCatcher96** [comment]
> 

Yes sir , send link and reply comment

**Comment by arshsisodiya** [comment]
> > 
> 
> Yes sir , send link and reply comment

Ok you aren't using FORCE_BOT_PM but
Are you using AUTO_DELETE_UPLOAD_MESSAGE

What's the value of  AUTO_DELETE_UPLOAD_MESSAGE_DURATION this var in your config.

**Comment by DreamCatcher96** [comment]
> > > 
> > 
> > 
> > Yes sir , send link and reply comment
> 
> Ok you aren't using FORCE_BOT_PM but Are you using AUTO_DELETE_UPLOAD_MESSAGE
> 
> What's the value of AUTO_DELETE_UPLOAD_MESSAGE_DURATION this var in your config.

It's your default  -1 , i am not change that

**Comment by DreamCatcher96** [comment]
> 

![IMG_20220828_200539](https://user-images.githubusercontent.com/63229691/187085986-63ad8b9b-48a6-47f7-8505-e598a02a31e4.jpg)

**Comment by arshsisodiya** [comment]
> ![Screenshot_2022-08-28-19-56-21-686_org telegram plus](https://user-images.githubusercontent.com/63229691/187085672-ea8ec855-4d73-4831-89c1-c4701471b73e.jpg) Long time iam trying to cancel this , but comment not respond

By looking at this message i can clearly see that you Edited the repo and it's not my repo

**Comment by DreamCatcher96** [comment]
> 

Yes , it's your repo iam not use other repo long time iam sing your repo , but some text iam make bold that's it

**Comment by DreamCatcher96** [comment]
![Screenshot_2022-08-29-00-53-13-470_org telegram plus](https://user-images.githubusercontent.com/63229691/187096023-723bb3ea-555b-4107-9069-e54f767eb4f1.jpg)

I forked new one same issue , not cancelled

**Comment by arshsisodiya** [comment]
i try to recreate the issue with the information you provided but i didn't face any issue, if it possible send the screen recording of the whole incident so that i can recreate the same situation again,
