### ISSUE TITLE
Is it possible?

### ISSUE THREAD

**Issue by BarrenWardo** [arshsisodiya/helios-mirror#131]
Can it be deployed on deta.sh?

Thank You.

**Comment by BarrenWardo** [comment]
++

Can it be done on getporter.dev also?

_P.S., not trying to irritate but instead trying to find a Heroku alternative for me & everyone_

**Comment by arshsisodiya** [comment]
Most service provider Don't allow mirror bots or have very less storage so it's next to impossible to deploy mirror bots on them, the best alternative after Heroku is VPS only.
