### ISSUE TITLE
Messages Getting Deleted 

### ISSUE THREAD

**Issue by GarouTheDevil** [arshsisodiya/helios-mirror#133]
When I Am Giving Mirror Task Or Leech Task
If The Resource Is Not Found
If I Cancel The Task
Bot Deleting The Link Which I Given Or The File Which I Am Mirroring
Inshort Bot Deleting My Messages
Fix It 
Thank You

**Comment by arshsisodiya** [comment]
Your Message Getting deleted because you are using AUTO_DELETE_UPLOAD_MESSAGE, set it to -1 and your message will not get deleted.

**Comment by GarouTheDevil** [comment]
Read My Message Properly Please
https://te.legra.ph/file/a4528a92e4f17f1385779.jpg
I Knew About Auto Delete Env

**Comment by GarouTheDevil** [comment]
Example : I Want To Mirror A Movie To Gdrive
And I Suddenly Want To Cancel It 
When I Given Cancel Cammand, Bot Not Only Stoping But Also Deleting The Movie Which I Wanted To Mirror

**Comment by arshsisodiya** [comment]
Read my comment properly with open eyes, I'm talking about AUTO_DELETE_UPLOAD_MESSAGE var, not AUTO_DELETE_MESSAGE, these are two different vars

**Comment by GarouTheDevil** [comment]
Let Me Give A Try I Dont Know About That
Well, Sorry
