### ISSUE TITLE
File Not Uploading in telegram

### ISSUE THREAD

**Issue by DextiNxD** [arshsisodiya/helios-mirror#19]
![image](https://user-images.githubusercontent.com/95567528/170659729-d158a5fc-3f02-49ea-b586-cafb982b96c6.png)
![image](https://user-images.githubusercontent.com/95567528/170659670-0d080b4f-b7b9-4822-b27c-3511c0d4b4ce.png)

Can you please solve this

**Comment by arshsisodiya** [comment]
Pyrogram error, will fix soon, although it's working fine here

**Comment by DextiNxD** [comment]
Ok
