### ISSUE TITLE
Error in telegraph

### ISSUE THREAD

**Issue by AshishSharma2006** [arshsisodiya/helios-mirror#22]
![image](https://user-images.githubusercontent.com/99271761/171519271-5a2077e7-cf10-4e22-a71c-dbbf3a98c612.png)

only showing drive link 😢
here's the link - https://telegra.ph/Samantha-06-01-9

**Comment by arshsisodiya** [comment]
No such issue is there, check if you setup index link correctly

**Comment by arshsisodiya** [comment]
For more Report in https://t.me/mirrorsociety

**Comment by AshishSharma2006** [comment]
> No such issue is there, check if you setup index link correctly

I checked by cloning both r working but in list only showing drive link
