### ISSUE TITLE
noob issue

### ISSUE THREAD

**Issue by geraltsmirror** [arshsisodiya/helios-mirror#29]
<img width="1440" alt="Screenshot 2022-06-09 at 5 34 17 PM" src="https://user-images.githubusercontent.com/107182915/172842814-fb9a33bb-96fb-46be-bf4f-3c1aa05776f6.png">

getting this error while mirrored file is uploading , can someone help

**Comment by geraltsmirror** [comment]
update : getting the error as below no
<img width="741" alt="Screenshot 2022-06-10 at 7 57 26 AM" src="https://user-images.githubusercontent.com/107182915/172978204-be69219d-2c17-468d-b808-2f8e52b1dde1.png">
w

**Comment by arshsisodiya** [comment]
Your TD and Token.pickle issue, generate token.pickle again
