### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by arjung24** [arshsisodiya/helios-mirror#36]
is it possible to log only media/video for leech log or mirror log??

**Comment by arshsisodiya** [comment]
You Can stop upload of Unwanted files using EXTENTION_FILTER,

**Comment by arjung24** [comment]
Ohh that's great idea

**Comment by arjung24** [comment]
Should i type like this

".txt .mp4 .avi"

??

**Comment by arshsisodiya** [comment]
Yes, like that,

**Comment by arjung24** [comment]
Another thing is brother, if u have time please check rss option. When running /leech command for rss it gets downloaded twice.
