### ISSUE TITLE
Why is it like this after uploading?

### ISSUE THREAD

**Issue by kawinpattanai** [arshsisodiya/helios-mirror#39]
How can I fix it?
![Screenshot_2022-06-17-22-50-20-76_469d9a8fb01100be319306c44b95b80a](https://user-images.githubusercontent.com/46213771/174333214-c62c2fbf-4e63-4ac4-ac9a-f7aedca6ade4.jpg)

**Comment by arshsisodiya** [comment]
I will look into it and fix it ASAP

**Comment by arshsisodiya** [comment]
Fixed Now
