### ISSUE TITLE
oracle?

### ISSUE THREAD

**Issue by carolynsteeves1** [arshsisodiya/helios-mirror#45]
What image should i use for oracle?

**Comment by Rajeshsahoo12** [comment]
I used this arshsisodiya/helioskirepo:arm64

As my vm instance is deployed on oracle cloud. And using linux server with ubuntu 22.04 LTS. And bot is working fine.

Hope this helps.

Thanks

**Comment by arshsisodiya** [comment]
Added  docker for oracle in Readme too its arshsisodiya/helioskirepo:arm64,
