### ISSUE TITLE
yt-dlp issue 

### ISSUE THREAD

**Issue by Nobody370** [arshsisodiya/helios-mirror#52]
https://www.youtube.com/playlist?list=PL9C64D8C420B1BF2F
![IMG_20220622_162551](https://user-images.githubusercontent.com/88897873/175130072-469a63ba-06f0-49eb-af70-0efe16ed3105.jpg)
![IMG_20220622_162700](https://user-images.githubusercontent.com/88897873/175130080-5a591b9e-6dd8-4335-87bf-923ad724dd26.jpg)
[log.txt](https://github.com/arshsisodiya/helios-mirror/files/8961078/log.txt)

**Comment by arshsisodiya** [comment]
I don't work for Yt-dlp sir, it's their issue they will fix it whenever they want, i can't do anything in it.
