### ISSUE TITLE
[Feature Request]  is it possible to implement task limit var in config ??

### ISSUE THREAD

**Issue by RealNoobieDrive** [arshsisodiya/helios-mirror#61]
will it possible to implement max task allowed   in bot ,so that we wont get memory exceed issue

**Comment by arshsisodiya** [comment]
https://github.com/arshsisodiya/helios-mirror/blob/master/aria.sh#L10 - --max-concurrent-downloads=15
https://github.com/arshsisodiya/helios-mirror/blob/master/qBittorrent/config/qBittorrent.conf#L32 
https://github.com/arshsisodiya/helios-mirror/blob/master/qBittorrent/config/qBittorrent.conf#L35 set it true

and edit the values according to your need and you are good to go

**Comment by RealNoobieDrive** [comment]
Thanks
