### ISSUE TITLE
[Improvement] qbmirror s issue

### ISSUE THREAD

**Issue by RealNoobieDrive** [arshsisodiya/helios-mirror#71]
when we use qbmirror s for downloading large  torrent file ,after downloading 1 part of file when we try to mirror second file ,it gives file/folder already in drive as stop-duplicate in on, so due to this we cant mirror remaining parts .. Is it possible to make stop-duplicate not work when using qbmirror s or any other way to resolve this issue .

**Comment by arshsisodiya** [comment]
Don't use Stop Duplicate in that Case.
