### ISSUE TITLE
Support for 4 GB TG Files

### ISSUE THREAD

**Issue by PBhadoo** [arshsisodiya/helios-mirror#73]
If possible add Support for Telegram Files using Premium Accounts. i.e. 4 GB.

**Comment by arshsisodiya** [comment]
Telegram Bot Api Doesn't support 4GB upload yet.

**Comment by PBhadoo** [comment]
I meant by using user account. Based on string session.

**Comment by arshsisodiya** [comment]
That i have to figure out and check

**Comment by arshsisodiya** [comment]
It's Not stable to add RN
BOT_PM and Leech Logs Will not work if More than 2 GB File was leeched, so better just leave it

**Comment by DextiNxD** [comment]
try using string session if want string session for test i will give

**Comment by PBhadoo** [comment]
Added by a friend. Works Great.

**Comment by arshsisodiya** [comment]
I Know it's Work great, But BOT_PM will not work,
