### ISSUE TITLE
#Warning_Error

### ISSUE THREAD

**Issue by codewithweeb** [arshsisodiya/helios-mirror#89]
![IMG_20220720_082312_303](https://user-images.githubusercontent.com/107316620/179887085-640da50c-92b8-404b-9ccd-d84aa41332f6.jpg)

there is warning that list index out of range on every mirror or leech command
note file is properly downloaded and also properly uploaded only there is warning in heroku is show

**Comment by codewithweeb** [comment]
i fixed it now👍👍

**Comment by codewithweeb** [comment]
uy

**Comment by arshsisodiya** [comment]
> i fixed it now👍👍

Make PR of fix🤞
