### ISSUE TITLE
Asking

### ISSUE THREAD

**Issue by Zusyaku** [arshsisodiya/helios-mirror#93]
Size Limits
TORRENT_DIRECT_LIMIT: To limit the Torrent/Direct mirror size. Don't add unit. Default unit is GB.
ZIP_UNZIP_LIMIT: To limit the size of zip and unzip commands. Don't add unit. Default unit is GB.
CLONE_LIMIT: To limit the size of Google Drive folder/file which you can clone. Don't add unit. Default unit is GB.
MEGA_LIMIT: To limit the size of Mega download. Don't add unit. Default unit is GB.
STORAGE_THRESHOLD: To leave specific storage free and any download will lead to leave free storage less than this value will be cancelled. Don't add unit. Default unit is GB.

How To Fill this under coloum here "30GB" ?????

       🠗
       🠗
       🠗
       V

# Size Limits
TORRENT_DIRECT_LIMIT = ""
ZIP_UNZIP_LIMIT = ""
CLONE_LIMIT = ""
MEGA_LIMIT = ""
STORAGE_THRESHOLD = ""

**Comment by arshsisodiya** [comment]
You only have to add value without unit ex - TORRENT_DIRECT_LIMIT = "30"
